// datasiswa.js
const daftarSiswa = [
    { username: "admin", password: "admin12345", nama: "ADMINISTRATOR", kelas: "ADMIN" },

    // KELAS XI-1
    { username: "ais754", password: "12345", nama: "AISYAH OKTA LIVINA LAURENZ", kelas: "XI-1" },
    { username: "aje214", password: "12345", nama: "AJENG ULANDARI", kelas: "XI-1" },
    { username: "aly125", password: "12345", nama: "ALYSA RANI ZALIANTI", kelas: "XI-1" },
    { username: "ame859", password: "12345", nama: "AMELIA JUNITA CAHYANI", kelas: "XI-1" },
    { username: "aur381", password: "12345", nama: "AURA CINTYA ARBIELA PUTRI", kelas: "XI-1" },
    { username: "azi350", password: "12345", nama: "AZIZIAH JACINDA RUELA MAHSA RAHMADI", kelas: "XI-1" },
    { username: "cac328", password: "12345", nama: "CACA HERLIANA PUTRI", kelas: "XI-1" },
    { username: "del242", password: "12345", nama: "DELA CAHYA MAULITA", kelas: "XI-1" },
    { username: "dev854", password: "12345", nama: "DEVI MARETA", kelas: "XI-1" },
    { username: "ega204", password: "12345", nama: "EGA FABIAN YAFA", kelas: "XI-1" },
    { username: "far792", password: "12345", nama: "FARELIO BRILYANSYAH", kelas: "XI-1" },
    { username: "flo858", password: "12345", nama: "FLORA AYU VALENCYA", kelas: "XI-1" },
    { username: "fre658", password: "12345", nama: "FREDYCO RAKA", kelas: "XI-1" },
    { username: "gil228", password: "12345", nama: "GILANG FITRAH DARMAWAN", kelas: "XI-1" },
    { username: "jay420", password: "12345", nama: "JAYANTI BUNGA LESTARI", kelas: "XI-1" },
    { username: "lea864", password: "12345", nama: "LEAVY AQEYLA AYATUL HUSNA", kelas: "XI-1" },
    { username: "mar382", password: "12345", nama: "MARVIN NAZALLUL ALVIZAR", kelas: "XI-1" },
    { username: "moh655", password: "12345", nama: "MOHM ANAS MALIKI", kelas: "XI-1" },
    { username: "mut533", password: "12345", nama: "MUTIARA SAFITRI MUSTOFA", kelas: "XI-1" },
    { username: "nab525", password: "12345", nama: "NABILA GABRELA PRADITA", kelas: "XI-1" },
    { username: "nab571", password: "12345", nama: "NABILA PUTRI AWALIA", kelas: "XI-1" },
    { username: "nai448", password: "12345", nama: "NAILA IZZA NURJANAH", kelas: "XI-1" },
    { username: "nai246", password: "12345", nama: "NAILA ZULFI AZ -ZAHRA", kelas: "XI-1" },
    { username: "nay905", password: "12345", nama: "NAYSILA DWI SASA BILA PUTRI SURYANTO", kelas: "XI-1" },
    { username: "naz725", password: "12345", nama: "NAZLAFATUL AZIZAH", kelas: "XI-1" },
    { username: "okt348", password: "12345", nama: "OKTA DWI NURAINI", kelas: "XI-1" },
    { username: "put299", password: "12345", nama: "PUTRI RIZQI RIA", kelas: "XI-1" },
    { username: "rer476", password: "12345", nama: "RERA MUSTIKA RESIMA", kelas: "XI-1" },
    { username: "ris404", password: "12345", nama: "RISMA AINYN NAFIAH", kelas: "XI-1" },
    { username: "san758", password: "12345", nama: "SANDY VIRZATULLAH", kelas: "XI-1" },
    { username: "suc693", password: "12345", nama: "SUCI LINTANG KINASIH", kelas: "XI-1" },
    { username: "van529", password: "12345", nama: "VANESA SEPTIANA PUTRI", kelas: "XI-1" },
    { username: "yor341", password: "12345", nama: "YORIZA DANISH SILVIERRA", kelas: "XI-1" },
    { username: "zel703", password: "12345", nama: "ZELIH AURELA", kelas: "XI-1" },
    { username: "amm566", password: "12345", nama: "AMMAR SAHADAT DIRGANTARA", kelas: "XI-1" },

    // KELAS XI-2
    { username: "alf604", password: "12345", nama: "ALFIDA HILDANA APRILIA", kelas: "XI-2" },
    { username: "ame529", password: "12345", nama: "AMELIA NG JIAXI-N", kelas: "XI-2" },
    { username: "ang494", password: "12345", nama: "ANGGUN VIRMA VIRNANDA DEVI", kelas: "XI-2" },
    { username: "ann201", password: "12345", nama: "ANNISA PUTRI ZHAKI", kelas: "XI-2" },
    { username: "avi102", password: "12345", nama: "AVIZA KIRANA PUTRI", kelas: "XI-2" },
    { username: "dea907", password: "12345", nama: "DEA NOVA LEONA DEWI", kelas: "XI-2" },
    { username: "din588", password: "12345", nama: "DINDA SEPTYANA DEWI", kelas: "XI-2" },
    { username: "div429", password: "12345", nama: "DIVA ALICIA PUTRI", kelas: "XI-2" },
    { username: "eka368", password: "12345", nama: "EKA RESA RAMADHANI", kelas: "XI-2" },
    { username: "feb172", password: "12345", nama: "FEBY PUTRI SUGIANSYAH", kelas: "XI-2" },
    { username: "fel148", password: "12345", nama: "FELCIA AGASI", kelas: "XI-2" },
    { username: "gey974", password: "12345", nama: "GEYSA HASTA SAPUTRA", kelas: "XI-2" },
    { username: "i g107", password: "12345", nama: "I GEDE PUTRA YASA", kelas: "XI-2" },
    { username: "kay483", password: "12345", nama: "KAYLA MARETHA PUTRI PUSPITARINI", kelas: "XI-2" },
    { username: "key389", password: "12345", nama: "KEYSHA ANINDITA", kelas: "XI-2" },
    { username: "len280", password: "12345", nama: "LENNY ZHIFILIA NUGRAHANI", kelas: "XI-2" },
    { username: "mey206", password: "12345", nama: "MEYKA NINDI AGUSTIN", kelas: "XI-2" },
    { username: "moh665", password: "12345", nama: "MOHAMMAD NATA MAURINO", kelas: "XI-2" },
    { username: "moh179", password: "12345", nama: "MOHAMAD ANDRIAN MAULANA", kelas: "XI-2" },
    { username: "muh254", password: "12345", nama: "MUHAMMAD IBRAHIMMOVIC", kelas: "XI-2" },
    { username: "muh605", password: "12345", nama: "MUHAMMAD WAHYU PUJI NUGRAHA", kelas: "XI-2" },
    { username: "muz682", password: "12345", nama: "MUZDHALIFA", kelas: "XI-2" },
    { username: "nad193", password: "12345", nama: "NADIFAH FARHANATUL MABRUROH", kelas: "XI-2" },
    { username: "nen473", password: "12345", nama: "NENG AYU JAVANZA QUINE YUANDRI", kelas: "XI-2" },
    { username: "rev254", password: "12345", nama: "REVY MAULIDA HASANAH", kelas: "XI-2" },
    { username: "ris698", password: "12345", nama: "RISKA MAULIDA ULFA", kelas: "XI-2" },
    { username: "rob471", password: "12345", nama: "ROBY JATI MURTI", kelas: "XI-2" },
    { username: "sal458", password: "12345", nama: "SALMA RAHADATUL AISY", kelas: "XI-2" },
    { username: "sen233", password: "12345", nama: "SENJA DINANTI", kelas: "XI-2" },
    { username: "sof688", password: "12345", nama: "SOFYAN ZAHURI A.", kelas: "XI-2" },
    { username: "van523", password: "12345", nama: "VANA AGISTA RAMADHANI", kelas: "XI-2" },
    { username: "wul158", password: "12345", nama: "WULIDATUL AFIFAH", kelas: "XI-2" },
    { username: "yen770", password: "12345", nama: "YENI DWI PRASTIYANI", kelas: "XI-2" },

    // KELAS XI-3
    { username: "ach237", password: "12345", nama: "ACHMAD FAIRUS RADITYA", kelas: "XI-3" },
    { username: "ald833", password: "12345", nama: "ALDERIO ILHAM QODZAFI", kelas: "XI-3" },
    { username: "alv891", password: "12345", nama: "ALVIAN MA'RIFATUL  ABROR", kelas: "XI-3" },
    { username: "ami148", password: "12345", nama: "AMIRAL JORDAN ARVA", kelas: "XI-3" },
    { username: "asy162", password: "12345", nama: "ASYAFA ZAHRA SALSABILLA", kelas: "XI-3" },
    { username: "aur143", password: "12345", nama: "AURA KIRANA MAULIDA", kelas: "XI-3" },
    { username: "che679", password: "12345", nama: "CHEISYA ANJELA PUTRI", kelas: "XI-3" },
    { username: "che133", password: "12345", nama: "CHEN LIXI-N NUR ZASKIA", kelas: "XI-3" },
    { username: "daf230", password: "12345", nama: "DAFA PARVAIZ Z.W", kelas: "XI-3" },
    { username: "dim774", password: "12345", nama: "DIMAS MAULANA", kelas: "XI-3" },
    { username: "dis314", password: "12345", nama: "DISTY EKA FEBIANA", kelas: "XI-3" },
    { username: "dit538", password: "12345", nama: "DITA KHARISMA DEWI", kelas: "XI-3" },
    { username: "div417", password: "12345", nama: "DIVA PUSPITA SARI", kelas: "XI-3" },
    { username: "fat476", password: "12345", nama: "FATHIR LANANG YOGATAMA", kelas: "XI-3" },
    { username: "fit708", password: "12345", nama: "FITRI NUR AINI", kelas: "XI-3" },
    { username: "fiz729", password: "12345", nama: "FIZA ARIF UQIANUS FAN", kelas: "XI-3" },
    { username: "fri434", password: "12345", nama: "FRISYA MAULIDA SANTIKA", kelas: "XI-3" },
    { username: "iga700", password: "12345", nama: "IGA MAHAREZA", kelas: "XI-3" },
    { username: "m.d168", password: "12345", nama: "M.DANAR IZHA ROHIL", kelas: "XI-3" },
    { username: "may285", password: "12345", nama: "MAYLA AURA ANDINI", kelas: "XI-3" },
    { username: "moh453", password: "12345", nama: "MOH RIDHO DZIKRULLAH", kelas: "XI-3" },
    { username: "moh971", password: "12345", nama: "MOHAMAD ALFIAN MAULANA", kelas: "XI-3" },
    { username: "muh328", password: "12345", nama: "MUHAMMAD KHOIRON THOIFUR ABDILLAH", kelas: "XI-3" },
    { username: "mut750", password: "12345", nama: "MUTIARA DWI A", kelas: "XI-3" },
    { username: "nad164", password: "12345", nama: "NADIN SYA PRAWESTI", kelas: "XI-3" },
    { username: "put609", password: "12345", nama: "PUTRI BUNGA CAHYANI", kelas: "XI-3" },
    { username: "ram620", password: "12345", nama: "RAMADHAN", kelas: "XI-3" },
    { username: "ris490", password: "12345", nama: "RISKA NOVITA P", kelas: "XI-3" },
    { username: "sel895", password: "12345", nama: "SELVIA JUNITA", kelas: "XI-3" },
    { username: "shi132", password: "12345", nama: "SHINTA METTA L. M", kelas: "XI-3" },
    { username: "wul105", password: "12345", nama: "WULAN CEISHA RAMADANI", kelas: "XI-3" },
    { username: "moh997", password: "12345", nama: "MOHAMMAD RAFFI ALFARIDZI ARDIANSYAH", kelas: "XI-3" },
    { username: "akh397", password: "12345", nama: "AKHMAD FAUZI FADILAH", kelas: "XI-3" },
    { username: "moh672", password: "12345", nama: "MOHAMMAD ARYA RADITYA", kelas: "XI-3" },
    { username: "feb663", password: "12345", nama: "FEBRI ARDIANSYAH PUTRA", kelas: "XI-3" },

    // KELAS XI-4
    { username: "and947", password: "12345", nama: "ANDRIANU DWI PUTRA KUSUMA", kelas: "XI-4" },
    { username: "ang490", password: "12345", nama: "ANGGITA FITRI FAUZIAH", kelas: "XI-4" },
    { username: "aul110", password: "12345", nama: "AULIA ZULFALITQ  PRATAMA", kelas: "XI-4" },
    { username: "aur703", password: "12345", nama: "AUREL JIHAN PANESA", kelas: "XI-4" },
    { username: "cat312", password: "12345", nama: "CATUR AHMAD HASYIM", kelas: "XI-4" },
    { username: "cit891", password: "12345", nama: "CITRA AYU VERGITA", kelas: "XI-4" },
    { username: "dha843", password: "12345", nama: "DHANIEL ARIFIN", kelas: "XI-4" },
    { username: "dhe186", password: "12345", nama: "DHEA BUNGA APRILLIA", kelas: "XI-4" },
    { username: "fra170", password: "12345", nama: "FRANDA APRILA WURI HARTONO", kelas: "XI-4" },
    { username: "gan369", password: "12345", nama: "GANTARI ZIA BHUMYAMCA", kelas: "XI-4" },
    { username: "han441", password: "12345", nama: "HANA FITRIA", kelas: "XI-4" },
    { username: "hol997", password: "12345", nama: "HOLIDA TUL FITRI", kelas: "XI-4" },
    { username: "ich321", password: "12345", nama: "ICHA IZZATUL JANNAH", kelas: "XI-4" },
    { username: "ket445", password: "12345", nama: "KETUT SONY LOKE BUDI WIGUNA", kelas: "XI-4" },
    { username: "m.i356", password: "12345", nama: "M.IBRA RAVITO", kelas: "XI-4" },
    { username: "moh842", password: "12345", nama: "MOH AZIZUL HILMI", kelas: "XI-4" },
    { username: "moh455", password: "12345", nama: "MOHAMMAD TORIQ HIDAYAH", kelas: "XI-4" },
    { username: "muh257", password: "12345", nama: "MUHAMMAD ARTHA MAU RIDO", kelas: "XI-4" },
    { username: "moh322", password: "12345", nama: "MOHAMMAD VALE SEPTINO ROSSI", kelas: "XI-4" },
    { username: "nan518", password: "12345", nama: "NANDA SASMITA", kelas: "XI-4" },
    { username: "nay103", password: "12345", nama: "NAYLA MUFIDA", kelas: "XI-4" },
    { username: "pon635", password: "12345", nama: "PONI AGRIANDARI", kelas: "XI-4" },
    { username: "rak783", password: "12345", nama: "RAKA PUTRA ANGGARA", kelas: "XI-4" },
    { username: "ris381", password: "12345", nama: "RISTA AYU PUTRI", kelas: "XI-4" },
    { username: "sep326", password: "12345", nama: "SEPTIAN SURYA RHOMADHONI", kelas: "XI-4" },
    { username: "sya898", password: "12345", nama: "SYAVA DYANI PUTRI", kelas: "XI-4" },
    { username: "val802", password: "12345", nama: "VALECIA ANGGRAENI SASMITA. P.", kelas: "XI-4" },
    { username: "vie390", password: "12345", nama: "VIERRA DIPUSPA DESHINTA SUGIONO", kelas: "XI-4" },
    { username: "waw105", password: "12345", nama: "WAWENDRA WAHYU BIMARTA", kelas: "XI-4" },
    { username: "zah460", password: "12345", nama: "ZAHRA THUSITA", kelas: "XI-4" },
    { username: "zel925", password: "12345", nama: "ZELVIA AYU VERASARI", kelas: "XI-4" },
    { username: "nov853", password: "12345", nama: "NOVA WIDIANTI", kelas: "XI-4" },
    { username: "moh218", password: "12345", nama: "MOHAMMAD ARIANSYAH", kelas: "XI-4" },
    { username: "fir432", password: "12345", nama: "FIRDAUS IBNU HADU", kelas: "XI-4" },

    // KELAS XI-5
    { username: "adi942", password: "12345", nama: "ADITYA RAMADHANI", kelas: "XI-5" },
    { username: "air902", password: "12345", nama: "AIRA NAFISATUL AINIYAH", kelas: "XI-5" },
    { username: "ald873", password: "12345", nama: "ALDI KURNIAWAN  SAPUTRA", kelas: "XI-5" },
    { username: "and967", password: "12345", nama: "ANDIKA PRASETYA", kelas: "XI-5" },
    { username: "ant801", password: "12345", nama: "ANTONIO JUNIOR LIWA PUTRA", kelas: "XI-5" },
    { username: "bun325", password: "12345", nama: "BUNGA RACHMATYAS MAHANI", kelas: "XI-5" },
    { username: "ces870", password: "12345", nama: "CESYA MAWRA PAWLINA SARI", kelas: "XI-5" },
    { username: "eko517", password: "12345", nama: "EKO HARIANTO", kelas: "XI-5" },
    { username: "era367", password: "12345", nama: "ERA FATRAVIA", kelas: "XI-5" },
    { username: "gei343", password: "12345", nama: "GEISHA DWI APRILIA", kelas: "XI-5" },
    { username: "gin526", password: "12345", nama: "GINA JIFARA WANGI", kelas: "XI-5" },
    { username: "kev374", password: "12345", nama: "KEVIN JULIANO SANDRA PRATAMA", kelas: "XI-5" },
    { username: "kik404", password: "12345", nama: "KIKI ROSA K", kelas: "XI-5" },
    { username: "lin697", password: "12345", nama: "LINDA TRI YULIYANI", kelas: "XI-5" },
    { username: "lut498", password: "12345", nama: "LUTFI ARIL PRAYOGA", kelas: "XI-5" },
    { username: "mau984", password: "12345", nama: "MAULANA ISHAK", kelas: "XI-5" },
    { username: "mey609", password: "12345", nama: "MEYLANIE ANGGI ZAZIVA", kelas: "XI-5" },
    { username: "moh654", password: "12345", nama: "MOH FAKHRI LUTFI", kelas: "XI-5" },
    { username: "muh548", password: "12345", nama: "MUH AFREZA SAPUTRA", kelas: "XI-5" },
    { username: "muh250", password: "12345", nama: "MUHAMMAD SAFI' I", kelas: "XI-5" },
    { username: "nau349", password: "12345", nama: "NAURA GELICIA T.", kelas: "XI-5" },
    { username: "nur566", password: "12345", nama: "NURUL IZZATI", kelas: "XI-5" },
    { username: "rah352", password: "12345", nama: "RAHMA INTAN PERMADHANI", kelas: "XI-5" },
    { username: "rah513", password: "12345", nama: "RAHMA TAUFIK RIDANI", kelas: "XI-5" },
    { username: "reg173", password: "12345", nama: "REGA TEGAR MAULANA HAKIKI", kelas: "XI-5" },
    { username: "saf436", password: "12345", nama: "SAFA TIARA", kelas: "XI-5" },
    { username: "ste583", password: "12345", nama: "STEFA RINA PUTRI ANINDITA", kelas: "XI-5" },
    { username: "ste865", password: "12345", nama: "STEFANI ANGELINA DARMANOTA", kelas: "XI-5" },
    { username: "sul952", password: "12345", nama: "SULUH PRABANDARU", kelas: "XI-5" },
    { username: "sye603", password: "12345", nama: "SYERILA SILFI MAULIDA", kelas: "XI-5" },
    { username: "tia453", password: "12345", nama: "TIARA AYU SABRINA", kelas: "XI-5" },
    { username: "wah353", password: "12345", nama: "WAHYU RIZKY", kelas: "XI-5" },
    { username: "yuy163", password: "12345", nama: "YUYUN ALFIANA", kelas: "XI-5" },
    { username: "nag692", password: "12345", nama: "NAGITA NUR OKTAVIANI", kelas: "XI-5" },
    { username: "dil166", password: "12345", nama: "DILA AGUS TIYA NEGSEH", kelas: "XI-5" },
    { username: "gyt528", password: "12345", nama: "GYTHA ATHIVA QANITA AZARIA", kelas: "XI-5" },

    // KELAS XI-6
    { username: "ach249", password: "12345", nama: "ACHAVA PUTRI ARIFANI", kelas: "XI-6" },
    { username: "ang795", password: "12345", nama: "ANGGUN TRI MULYANI", kelas: "XI-6" },
    { username: "ary769", password: "12345", nama: "ARYAN DWI NURBEKTI", kelas: "XI-6" },
    { username: "bay473", password: "12345", nama: "BAYU PUTRA RAMADHAN", kelas: "XI-6" },
    { username: "cah235", password: "12345", nama: "CAHYARANI FATUROHMAH", kelas: "XI-6" },
    { username: "dha787", password: "12345", nama: "DHANIEL ARIFIN", kelas: "XI-6" },
    { username: "fah869", password: "12345", nama: "FAHRIZAL BAHTIAR HAMZAH", kelas: "XI-6" },
    { username: "fah867", password: "12345", nama: "FAHZA ALIYA PUTRI", kelas: "XI-6" },
    { username: "faz648", password: "12345", nama: "FAZA ASKIA TAMMA", kelas: "XI-6" },
    { username: "fel195", password: "12345", nama: "FELIZA ARTHA JASMINE", kelas: "XI-6" },
    { username: "fer766", password: "12345", nama: "FERDY ID ANDRE YANTO", kelas: "XI-6" },
    { username: "gal497", password: "12345", nama: "GALUH SAPUTRI", kelas: "XI-6" },
    { username: "jes654", password: "12345", nama: "JESSI TIRTA DHARMA AYU PUSPA  YOGI", kelas: "XI-6" },
    { username: "lav414", password: "12345", nama: "LAVENIA VEGA PUTRI MANIK", kelas: "XI-6" },
    { username: "m a824", password: "12345", nama: "M ANDY BEGARRT PRASSETYO", kelas: "XI-6" },
    { username: "m p652", password: "12345", nama: "M PRIYA DANIEL W", kelas: "XI-6" },
    { username: "mar383", password: "12345", nama: "MARSYA DWI SAPUTRI", kelas: "XI-6" },
    { username: "moh664", password: "12345", nama: "MOH ARLYN DWI ANDIKA", kelas: "XI-6" },
    { username: "moh524", password: "12345", nama: "MOH DANIAL HERDYANSAH", kelas: "XI-6" },
    { username: "moh173", password: "12345", nama: "MOH RAFKA EKA MANNANSYAH", kelas: "XI-6" },
    { username: "moh439", password: "12345", nama: "MOH RIFKI NUR HIDAYAT", kelas: "XI-6" },
    { username: "moh680", password: "12345", nama: "MOHAMAD FAHREZI", kelas: "XI-6" },
    { username: "put327", password: "12345", nama: "PUTRI AURA MARGARETA", kelas: "XI-6" },
    { username: "rah514", password: "12345", nama: "RAHEL NILUH AGUSTINA", kelas: "XI-6" },
    { username: "ram817", password: "12345", nama: "RAMADHANI TEGAR PAMUJI", kelas: "XI-6" },
    { username: "rey633", password: "12345", nama: "REYNO ARVENTA HADIN PRATAMA", kelas: "XI-6" },
    { username: "sas135", password: "12345", nama: "SASKIA PUTRI CAHYANINGTYAS", kelas: "XI-6" },
    { username: "sep743", password: "12345", nama: "SEPTINA AULIYA RAMADANI", kelas: "XI-6" },
    { username: "sey232", password: "12345", nama: "SEYLA ERFA AMANDA PUTRI", kelas: "XI-6" },
    { username: "sof689", password: "12345", nama: "SOFIATUL AZIZAH", kelas: "XI-6" },
    { username: "wan230", password: "12345", nama: "WANDA PUTRI", kelas: "XI-6" },
    { username: "din312", password: "12345", nama: "DINDA SEKAR RUMI", kelas: "XI-6" },
    { username: "alv541", password: "12345", nama: "ALVINO GANESHA PUTRA", kelas: "XI-6" },
    { username: "myi163", password: "12345", nama: "MYISHA AMELIA JAUHARI", kelas: "XI-6" },
    { username: "wif157", password: "12345", nama: "WIFA RIZKI RAMADANI", kelas: "XI-6" },
    { username: "wid667", password: "12345", nama: "WIDYA JULITA SAPUTRI", kelas: "XI-6" }
];
