// datasiswa.js
const daftarSiswa = [
    // KELAS XI-1
    { username: "aisyah1", password: "123", nama: "AISYAH OKTA LIVINA LAURENZ", kelas: "XI-1" },
    { username: "ajeng2", password: "123", nama: "AJENG ULANDARI", kelas: "XI-1" },
    { username: "alysa3", password: "123", nama: "ALYSA RANI ZALIANTI", kelas: "XI-1" },
    { username: "amelia4", password: "123", nama: "AMELIA JUNITA CAHYANI", kelas: "XI-1" },
    { username: "aura5", password: "123", nama: "AURA CINTYA ARBIELA PUTRI", kelas: "XI-1" },
    { username: "aziziah6", password: "123", nama: "AZIZIAH JACINDA RUELA MAHSA RAHMADI", kelas: "XI-1" },
    { username: "caca7", password: "123", nama: "CACA HERLIANA PUTRI", kelas: "XI-1" },
    { username: "dela8", password: "123", nama: "DELA CAHYA MAULITA", kelas: "XI-1" },
    { username: "devi9", password: "123", nama: "DEVI MARETA", kelas: "XI-1" },
    { username: "ega10", password: "123", nama: "EGA FABIAN YAFA", kelas: "XI-1" },
    { username: "farelio11", password: "123", nama: "FARELIO BRILYANSYAH", kelas: "XI-1" },
    { username: "flora12", password: "123", nama: "FLORA AYU VALENCYA", kelas: "XI-1" },
    { username: "fredyco13", password: "123", nama: "FREDYCO RAKA", kelas: "XI-1" },
    { username: "gilang14", password: "123", nama: "GILANG FITRAH DARMAWAN", kelas: "XI-1" },
    { username: "jayanti15", password: "123", nama: "JAYANTI BUNGA LESTARI", kelas: "XI-1" },
    { username: "leavy16", password: "123", nama: "LEAVY AQEYLA AYATUL HUSNA", kelas: "XI-1" },
    { username: "marvin17", password: "123", nama: "MARVIN NAZALLUL ALVIZAR", kelas: "XI-1" },
    { username: "mohm18", password: "123", nama: "MOHM ANAS MALIKI", kelas: "XI-1" },
    { username: "mutiara19", password: "123", nama: "MUTIARA SAFITRI MUSTOFA", kelas: "XI-1" },
    { username: "nabila20", password: "123", nama: "NABILA GABRELA PRADITA", kelas: "XI-1" },
    { username: "nabila21", password: "123", nama: "NABILA PUTRI AWALIA", kelas: "XI-1" },
    { username: "naila22", password: "123", nama: "NAILA IZZA NURJANAH", kelas: "XI-1" },
    { username: "naila23", password: "123", nama: "NAILA ZULFI AZ -ZAHRA", kelas: "XI-1" },
    { username: "naysila24", password: "123", nama: "NAYSILA DWI SASA BILA PUTRI SURYANTO", kelas: "XI-1" },
    { username: "nazlafatul25", password: "123", nama: "NAZLAFATUL AZIZAH", kelas: "XI-1" },
    { username: "okta26", password: "123", nama: "OKTA DWI NURAINI", kelas: "XI-1" },
    { username: "putri27", password: "123", nama: "PUTRI RIZQI RIA", kelas: "XI-1" },
    { username: "rera28", password: "123", nama: "RERA MUSTIKA RESIMA", kelas: "XI-1" },
    { username: "risma29", password: "123", nama: "RISMA AINYN NAFIAH", kelas: "XI-1" },
    { username: "sandy30", password: "123", nama: "SANDY VIRZATULLAH", kelas: "XI-1" },
    { username: "suci31", password: "123", nama: "SUCI LINTANG KINASIH", kelas: "XI-1" },
    { username: "vanesa32", password: "123", nama: "VANESA SEPTIANA PUTRI", kelas: "XI-1" },
    { username: "yoriza33", password: "123", nama: "YORIZA DANISH SILVIERRA", kelas: "XI-1" },
    { username: "zelih34", password: "123", nama: "ZELIH AURELA", kelas: "XI-1" },
    { username: "ammar35", password: "123", nama: "AMMAR SAHADAT DIRGANTARA", kelas: "XI-1" },

    // KELAS XI-2
    { username: "alfida36", password: "123", nama: "ALFIDA HILDANA APRILIA", kelas: "XI-2" },
    { username: "amelia37", password: "123", nama: "AMELIA NG JIAXI-N", kelas: "XI-2" },
    { username: "anggun38", password: "123", nama: "ANGGUN VIRMA VIRNANDA DEVI", kelas: "XI-2" },
    { username: "annisa39", password: "123", nama: "ANNISA PUTRI ZHAKI", kelas: "XI-2" },
    { username: "aviza40", password: "123", nama: "AVIZA KIRANA PUTRI", kelas: "XI-2" },
    { username: "dea41", password: "123", nama: "DEA NOVA LEONA DEWI", kelas: "XI-2" },
    { username: "dinda42", password: "123", nama: "DINDA SEPTYANA DEWI", kelas: "XI-2" },
    { username: "diva43", password: "123", nama: "DIVA ALICIA PUTRI", kelas: "XI-2" },
    { username: "eka44", password: "123", nama: "EKA RESA RAMADHANI", kelas: "XI-2" },
    { username: "feby45", password: "123", nama: "FEBY PUTRI SUGIANSYAH", kelas: "XI-2" },
    { username: "felcia46", password: "123", nama: "FELCIA AGASI", kelas: "XI-2" },
    { username: "geysa47", password: "123", nama: "GEYSA HASTA SAPUTRA", kelas: "XI-2" },
    { username: "igede48", password: "123", nama: "I GEDE PUTRA YASA", kelas: "XI-2" },
    { username: "kayla49", password: "123", nama: "KAYLA MARETHA PUTRI PUSPITARINI", kelas: "XI-2" },
    { username: "keysha50", password: "123", nama: "KEYSHA ANINDITA", kelas: "XI-2" },
    { username: "lenny51", password: "123", nama: "LENNY ZHIFILIA NUGRAHANI", kelas: "XI-2" },
    { username: "meyka52", password: "123", nama: "MEYKA NINDI AGUSTIN", kelas: "XI-1" },
    { username: "mohammad53", password: "123", nama: "MOHAMMAD NATA MAURINO", kelas: "XI-2" },
    { username: "mohamad54", password: "123", nama: "MOHAMAD ANDRIAN MAULANA", kelas: "XI-2" },
    { username: "muhammad55", password: "123", nama: "MUHAMMAD IBRAHIMMOVIC", kelas: "XI-2" },
    { username: "muhammad56", password: "123", nama: "MUHAMMAD WAHYU PUJI NUGRAHA", kelas: "XI-2" },
    { username: "muzdhalifa57", password: "123", nama: "MUZDHALIFA", kelas: "XI-2" },
    { username: "nadifah58", password: "123", nama: "NADIFAH FARHANATUL MABRUROH", kelas: "XI-2" },
    { username: "neng59", password: "123", nama: "NENG AYU JAVANZA QUINE YUANDRI", kelas: "XI-2" },
    { username: "revy60", password: "123", nama: "REVY MAULIDA HASANAH", kelas: "XI-2" },
    { username: "riska61", password: "123", nama: "RISKA MAULIDA ULFA", kelas: "XI-2" },
    { username: "roby62", password: "123", nama: "ROBY JATI MURTI", kelas: "XI-2" },
    { username: "salma63", password: "123", nama: "SALMA RAHADATUL AISY", kelas: "XI-2" },
    { username: "senja64", password: "123", nama: "SENJA DINANTI", kelas: "XI-2" },
    { username: "sofyan65", password: "123", nama: "SOFYAN ZAHURI A.", kelas: "XI-2" },
    { username: "vana66", password: "123", nama: "VANA AGISTA RAMADHANI", kelas: "XI-2" },
    { username: "wulidatul67", password: "123", nama: "WULIDATUL AFIFAH", kelas: "XI-2" },
    { username: "yeni68", password: "123", nama: "YENI DWI PRASTIYANI", kelas: "XI-2" },
    { username: "msueltan69", password: "123", nama: "M. SUELTAN SOFYAN ARRIDHO", kelas: "XI-2" },

    // KELAS XI-3
    { username: "achmad70", password: "123", nama: "ACHMAD FAIRUS RADITYA", kelas: "XI-3" },
    { username: "alderio71", password: "123", nama: "ALDERIO ILHAM QODZAFI", kelas: "XI-3" },
    { username: "alvian72", password: "123", nama: "ALVIAN MA'RIFATUL  ABROR", kelas: "XI-3" },
    { username: "amiral73", password: "123", nama: "AMIRAL JORDAN ARVA", kelas: "XI-3" },
    { username: "asyafa74", password: "123", nama: "ASYAFA ZAHRA SALSABILLA", kelas: "XI-3" },
    { username: "aura75", password: "123", nama: "AURA KIRANA MAULIDA", kelas: "XI-3" },
    { username: "cheisya76", password: "123", nama: "CHEISYA ANJELA PUTRI", kelas: "XI-3" },
    { username: "chen77", password: "123", nama: "CHEN LIXI-N NUR ZASKIA", kelas: "XI-3" },
    { username: "dafa78", password: "123", nama: "DAFA PARVAIZ Z.W", kelas: "XI-3" },
    { username: "dimas79", password: "123", nama: "DIMAS MAULANA", kelas: "XI-3" },
    { username: "disty80", password: "123", nama: "DISTY EKA FEBIANA", kelas: "XI-3" },
    { username: "dita81", password: "123", nama: "DITA KHARISMA DEWI", kelas: "XI-3" },
    { username: "diva82", password: "123", nama: "DIVA PUSPITA SARI", kelas: "XI-3" },
    { username: "fathir83", password: "123", nama: "FATHIR LANANG YOGATAMA", kelas: "XI-3" },
    { username: "fitri84", password: "123", nama: "FITRI NUR AINI", kelas: "XI-3" },
    { username: "fiza85", password: "123", nama: "FIZA ARIF UQIANUS FAN", kelas: "XI-3" },
    { username: "frisya86", password: "123", nama: "FRISYA MAULIDA SANTIKA", kelas: "XI-3" },
    { username: "iga87", password: "123", nama: "IGA MAHAREZA", kelas: "XI-3" },
    { username: "mdanar88", password: "123", nama: "M.DANAR IZHA ROHIL", kelas: "XI-3" },
    { username: "mayla89", password: "123", nama: "MAYLA AURA ANDINI", kelas: "XI-3" },
    { username: "moh90", password: "123", nama: "MOH RIDHO DZIKRULLAH", kelas: "XI-3" },
    { username: "mohamad91", password: "123", nama: "MOHAMAD ALFIAN MAULANA", kelas: "XI-3" },
    { username: "muhammad92", password: "123", nama: "MUHAMMAD KHOIRON THOIFUR ABDILLAH", kelas: "XI-3" },
    { username: "mutiara93", password: "123", nama: "MUTIARA DWI A", kelas: "XI-3" },
    { username: "nadin94", password: "123", nama: "NADIN SYA PRAWESTI", kelas: "XI-3" },
    { username: "putri95", password: "123", nama: "PUTRI BUNGA CAHYANI", kelas: "XI-3" },
    { username: "ramadhan96", password: "123", nama: "RAMADHAN", kelas: "XI-3" },
    { username: "riska97", password: "123", nama: "RISKA NOVITA P", kelas: "XI-3" },
    { username: "selvia98", password: "123", nama: "SELVIA JUNITA", kelas: "XI-3" },
    { username: "shinta99", password: "123", nama: "SHINTA METTA L. M", kelas: "XI-3" },
    { username: "wulan100", password: "123", nama: "WULAN CEISHA RAMADANI", kelas: "XI-3" },
    { username: "mohammad101", password: "123", nama: "MOHAMMAD RAFFI ALFARIDZI ARDIANSYAH", kelas: "XI-3" },
    { username: "akhmad102", password: "123", nama: "AKHMAD FAUZI FADILAH", kelas: "XI-3" },
    { username: "mohammad103", password: "123", nama: "MOHAMMAD ARYA RADITYA", kelas: "XI-3" },
    { username: "febri104", password: "123", nama: "FEBRI ARDIANSYAH PUTRA", kelas: "XI-3" },

    // KELAS XI-4
    { username: "andrianu105", password: "123", nama: "ANDRIANU DWI PUTRA KUSUMA", kelas: "XI-4" },
    { username: "anggita106", password: "123", nama: "ANGGITA FITRI FAUZIAH", kelas: "XI-4" },
    { username: "aulia107", password: "123", nama: "AULIA ZULFALITQ  PRATAMA", kelas: "XI-4" },
    { username: "aurel108", password: "123", nama: "AUREL JIHAN PANESA", kelas: "XI-4" },
    { username: "catur109", password: "123", nama: "CATUR AHMAD HASYIM", kelas: "XI-4" },
    { username: "citra110", password: "123", nama: "CITRA AYU VERGITA", kelas: "XI-4" },
    { username: "dhaniel111", password: "123", nama: "DHANIEL ARIFIN", kelas: "XI-4" },
    { username: "dhea112", password: "123", nama: "DHEA BUNGA APRILLIA", kelas: "XI-4" },
    { username: "franda113", password: "123", nama: "FRANDA APRILA WURI HARTONO", kelas: "XI-4" },
    { username: "gantari114", password: "123", nama: "GANTARI ZIA BHUMYAMCA", kelas: "XI-4" },
    { username: "hana115", password: "123", nama: "HANA FITRIA", kelas: "XI-4" },
    { username: "holida116", password: "123", nama: "HOLIDA TUL FITRI", kelas: "XI-4" },
    { username: "icha117", password: "123", nama: "ICHA IZZATUL JANNAH", kelas: "XI-4" },
    { username: "ketut118", password: "123", nama: "KETUT SONY LOKE BUDI WIGUNA", kelas: "XI-4" },
    { username: "mibra119", password: "123", nama: "M.IBRA RAVITO", kelas: "XI-4" },
    { username: "moh120", password: "123", nama: "MOH AZIZUL HILMI", kelas: "XI-4" },
    { username: "mohammad121", password: "123", nama: "MOHAMMAD TORIQ HIDAYAH", kelas: "XI-4" },
    { username: "muhammad122", password: "123", nama: "MUHAMMAD ARTHA MAU RIDO", kelas: "XI-4" },
    { username: "mohammad123", password: "123", nama: "MOHAMMAD VALE SEPTINO ROSSI", kelas: "XI-4" },
    { username: "nanda124", password: "123", nama: "NANDA SASMITA", kelas: "XI-4" },
    { username: "nayla125", password: "123", nama: "NAYLA MUFIDA", kelas: "XI-4" },
    { username: "poni126", password: "123", nama: "PONI AGRIANDARI", kelas: "XI-4" },
    { username: "raka127", password: "123", nama: "RAKA PUTRA ANGGARA", kelas: "XI-4" },
    { username: "rista128", password: "123", nama: "RISTA AYU PUTRI", kelas: "XI-4" },
    { username: "septian129", password: "123", nama: "SEPTIAN SURYA RHOMADHONI", kelas: "XI-4" },
    { username: "syava130", password: "123", nama: "SYAVA DYANI PUTRI", kelas: "XI-4" },
    { username: "valecia131", password: "123", nama: "VALECIA ANGGRAENI SASMITA. P.", kelas: "XI-4" },
    { username: "vierra132", password: "123", nama: "VIERRA DIPUSPA DESHINTA SUGIONO", kelas: "XI-4" },
    { username: "wawendra133", password: "123", nama: "WAWENDRA WAHYU BIMARTA", kelas: "XI-4" },
    { username: "zahra134", password: "123", nama: "ZAHRA THUSITA", kelas: "XI-4" },
    { username: "zelvia135", password: "123", nama: "ZELVIA AYU VERASARI", kelas: "XI-4" },
    { username: "nova136", password: "123", nama: "NOVA WIDIANTI", kelas: "XI-4" },
    { username: "mohammad137", password: "123", nama: "MOHAMMAD ARIANSYAH", kelas: "XI-4" },
    { username: "firdaus138", password: "123", nama: "FIRDAUS IBNU HADU", kelas: "XI-4" },

    // KELAS XI-5
    { username: "aditya139", password: "123", nama: "ADITYA RAMADHANI", kelas: "XI-5" },
    { username: "aira140", password: "123", nama: "AIRA NAFISATUL AINIYAH", kelas: "XI-5" },
    { username: "aldi141", password: "123", nama: "ALDI KURNIAWAN  SAPUTRA", kelas: "XI-5" },
    { username: "andika142", password: "123", nama: "ANDIKA PRASETYA", kelas: "XI-5" },
    { username: "antonio143", password: "123", nama: "ANTONIO JUNIOR LIWA PUTRA", kelas: "XI-5" },
    { username: "bunga144", password: "123", nama: "BUNGA RACHMATYAS MAHANI", kelas: "XI-5" },
    { username: "cesya145", password: "123", nama: "CESYA MAWRA PAWLINA SARI", kelas: "XI-5" },
    { username: "eko146", password: "123", nama: "EKO HARIANTO", kelas: "XI-5" },
    { username: "era147", password: "123", nama: "ERA FATRAVIA", kelas: "XI-5" },
    { username: "geisha148", password: "123", nama: "GEISHA DWI APRILIA", kelas: "XI-5" },
    { username: "gina149", password: "123", nama: "GINA JIFARA WANGI", kelas: "XI-5" },
    { username: "kevin150", password: "123", nama: "KEVIN JULIANO SANDRA PRATAMA", kelas: "XI-5" },
    { username: "kiki151", password: "123", nama: "KIKI ROSA K", kelas: "XI-5" },
    { username: "linda152", password: "123", nama: "LINDA TRI YULIYANI", kelas: "XI-5" },
    { username: "lutfi153", password: "123", nama: "LUTFI ARIL PRAYOGA", kelas: "XI-5" },
    { username: "maulana154", password: "123", nama: "MAULANA ISHAK", kelas: "XI-5" },
    { username: "meylanie155", password: "123", nama: "MEYLANIE ANGGI ZAZIVA", kelas: "XI-5" },
    { username: "moh156", password: "123", nama: "MOH FAKHRI LUTFI", kelas: "XI-5" },
    { username: "muh157", password: "123", nama: "MUH AFREZA SAPUTRA", kelas: "XI-5" },
    { username: "muhammad158", password: "123", nama: "MUHAMMAD SAFI' I", kelas: "XI-5" },
    { username: "naura159", password: "123", nama: "NAURA GELICIA T.", kelas: "XI-5" },
    { username: "nurul160", password: "123", nama: "NURUL IZZATI", kelas: "XI-5" },
    { username: "rahma161", password: "123", nama: "RAHMA INTAN PERMADHANI", kelas: "XI-5" },
    { username: "rahma162", password: "123", nama: "RAHMA TAUFIK RIDANI", kelas: "XI-5" },
    { username: "rega163", password: "123", nama: "REGA TEGAR MAULANA HAKIKI", kelas: "XI-5" },
    { username: "safa164", password: "123", nama: "SAFA TIARA", kelas: "XI-5" },
    { username: "stefa165", password: "123", nama: "STEFA RINA PUTRI ANINDITA", kelas: "XI-5" },
    { username: "stefani166", password: "123", nama: "STEFANI ANGELINA DARMANOTA", kelas: "XI-5" },
    { username: "suluh167", password: "123", nama: "SULUH PRABANDARU", kelas: "XI-5" },
    { username: "syerila168", password: "123", nama: "SYERILA SILFI MAULIDA", kelas: "XI-5" },
    { username: "tiara169", password: "123", nama: "TIARA AYU SABRINA", kelas: "XI-5" },
    { username: "wahyu170", password: "123", nama: "WAHYU RIZKY", kelas: "XI-5" },
    { username: "yuyun171", password: "123", nama: "YUYUN ALFIANA", kelas: "XI-5" },
    { username: "nagita172", password: "123", nama: "NAGITA NUR OKTAVIANI", kelas: "XI-5" },
    { username: "dila173", password: "123", nama: "DILA AGUS TIYA NEGSEH", kelas: "XI-5" },
    { username: "gytha174", password: "123", nama: "GYTHA ATHIVA QANITA AZARIA", kelas: "XI-5" },

    // KELAS XI-6
    { username: "achava175", password: "123", nama: "ACHAVA PUTRI ARIFANI", kelas: "XI-6" },
    { username: "anggun176", password: "123", nama: "ANGGUN TRI MULYANI", kelas: "XI-6" },
    { username: "aryan177", password: "123", nama: "ARYAN DWI NURBEKTI", kelas: "XI-6" },
    { username: "bayu178", password: "123", nama: "BAYU PUTRA RAMADHAN", kelas: "XI-6" },
    { username: "cahyarani179", password: "123", nama: "CAHYARANI FATUROHMAH", kelas: "XI-6" },
    { username: "dhaniel180", password: "123", nama: "DHANIEL ARIFIN", kelas: "XI-6" },
    { username: "fahrizal181", password: "123", nama: "FAHRIZAL BAHTIAR HAMZAH", kelas: "XI-6" },
    { username: "fahza182", password: "123", nama: "FAHZA ALIYA PUTRI", kelas: "XI-6" },
    { username: "faza183", password: "123", nama: "FAZA ASKIA TAMMA", kelas: "XI-6" },
    { username: "feliza184", password: "123", nama: "FELIZA ARTHA JASMINE", kelas: "XI-6" },
    { username: "ferdy185", password: "123", nama: "FERDY ID ANDRE YANTO", kelas: "XI-6" },
    { username: "galuh186", password: "123", nama: "GALUH SAPUTRI", kelas: "XI-6" },
    { username: "jessi187", password: "123", nama: "JESSI TIRTA DHARMA AYU PUSPA  YOGI", kelas: "XI-6" },
    { username: "lavenia188", password: "123", nama: "LAVENIA VEGA PUTRI MANIK", kelas: "XI-6" },
    { username: "mandy189", password: "123", nama: "M ANDY BEGARRT PRASSETYO", kelas: "XI-6" },
    { username: "mpriya190", password: "123", nama: "M PRIYA DANIEL W", kelas: "XI-6" },
    { username: "marsya191", password: "123", nama: "MARSYA DWI SAPUTRI", kelas: "XI-6" },
    { username: "moh192", password: "123", nama: "MOH ARLYN DWI ANDIKA", kelas: "XI-6" },
    { username: "moh193", password: "123", nama: "MOH DANIAL HERDYANSAH", kelas: "XI-6" },
    { username: "moh194", password: "123", nama: "MOH RAFKA EKA MANNANSYAH", kelas: "XI-6" },
    { username: "moh195", password: "123", nama: "MOH RIFKI NUR HIDAYAT", kelas: "XI-6" },
    { username: "mohamad196", password: "123", nama: "MOHAMAD FAHREZI", kelas: "XI-6" },
    { username: "putri197", password: "123", nama: "PUTRI AURA MARGARETA", kelas: "XI-6" },
    { username: "rahel198", password: "123", nama: "RAHEL NILUH AGUSTINA", kelas: "XI-6" },
    { username: "ramadhani199", password: "123", nama: "RAMADHANI TEGAR PAMUJI", kelas: "XI-6" },
    { username: "reyno200", password: "123", nama: "REYNO ARVENTA HADIN PRATAMA", kelas: "XI-6" },
    { username: "saskia201", password: "123", nama: "SASKIA PUTRI CAHYANINGTYAS", kelas: "XI-6" },
    { username: "septina202", password: "123", nama: "SEPTINA AULIYA RAMADANI", kelas: "XI-6" },
    { username: "seyla203", password: "123", nama: "SEYLA ERFA AMANDA PUTRI", kelas: "XI-6" },
    { username: "sofiatul204", password: "123", nama: "SOFIATUL AZIZAH", kelas: "XI-6" },
    { username: "wanda205", password: "123", nama: "WANDA PUTRI", kelas: "XI-6" },
    { username: "dinda206", password: "123", nama: "DINDA SEKAR RUMI", kelas: "XI-6" },
    { username: "alvino207", password: "123", nama: "ALVINO GANESHA PUTRA", kelas: "XI-6" },
    { username: "myisha208", password: "123", nama: "MYISHA AMELIA JAUHARI", kelas: "XI-6" },
    { username: "wifa209", password: "123", nama: "WIFA RIZKI RAMADANI", kelas: "XI-6" },
    { username: "widya210", password: "123", nama: "WIDYA JULITA SAPUTRI", kelas: "XI-6" }
];
